### ISSUE TITLE
Archer C64 Support Data

### ISSUE THREAD

**Issue by mahatm73** [AlexandrErohin/TP-Link-Archer-C6U#38] opened 2024-09-19 13:48 UTC
List of buttons clicked on in the router management page
[192.168.7.1.har.tar.gz](https://github.com/user-attachments/files/17060138/192.168.7.1.har.tar.gz)

**Comment by AlexandrErohin** [comment] 2024-09-19 18:47
Hi.
Unfortunately, all request are encrypted and I cannot parse them without having this router

Would be great if you could add support for your router by creating PR with new class that extends AbstractRouter https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L19

This Issue is duplicate of https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/23

**Closed by AlexandrErohin** 2024-09-19 18:47 UTC

**Comment by mahatm73** [comment] 2024-09-20 12:18
Добрый день
а есть инструкция как это сделать?

чт, 19 сент. 2024 г. в 21:48, AlexandrErohin ***@***.***>:
