### ISSUE TITLE
Archer C64 Support Data

### ISSUE THREAD

**Issue by MadMilax** [AlexandrErohin/TP-Link-Archer-C6U#37] opened 2024-09-15 19:42 UTC
Buttons: internet; wireless; wireless setting; system; operating mode; network map; clients; logout
[Uploading Archer C64.zip…]()

**Comment by MadMilax** [comment] 2024-09-15 19:47
Firmware Version:
1.13.2 Build 230824 Rel.74702n(4D45)

Hardware Version:
Archer C64 1.0

Mode:
Access Point Mode (Current)

**Comment by MadMilax** [comment] 2024-09-15 19:52
[Archer C64.zip](https://github.com/user-attachments/files/17007187/Archer.C64.zip)

**Comment by AlexandrErohin** [comment] 2024-09-16 11:24
Hi.
Unfortunately, all request are encrypted and I cannot parse them without having this router

Would be great if you could add support for your router by creating PR with new class that extends AbstractRouter https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L19

This Issue is duplicate of https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/23

**Closed by AlexandrErohin** 2024-09-16 11:24 UTC
