### ISSUE TITLE
Support for C6V4 router

### ISSUE THREAD

**Issue by EPeterE** [AlexandrErohin/TP-Link-Archer-C6U#47] opened 2024-10-22 12:20 UTC
Hi. I get this message, but unsure how to create the files you require to support the router. Thanks
![image_2024-10-22_142022537](https://github.com/user-attachments/assets/cbe3c78c-8796-42e8-aa2b-67195db65672)

**Comment by AlexandrErohin** [comment] 2024-10-22 13:09
Hi. You need to implement this class https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L658

**Comment by AlexandrErohin** [comment] 2024-10-22 13:09
This issue is duplicate of https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/15

**Closed by AlexandrErohin** 2024-10-22 13:09 UTC

**Comment by AlexandrErohin** [comment] 2024-10-22 17:00
For example: TplinkC6V4Router has get_status method. You need to write a code there to get router status info. Like TPLinkDecoClient method get_status https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L543

**Comment by EPeterE** [comment] 2024-10-22 17:07
Ok, that is beyond my skillset. Thanks
