### ISSUE TITLE
Test with archer C80

### ISSUE THREAD

**Issue by jlguibourg** [AlexandrErohin/TP-Link-Archer-C6U#7] opened 2024-01-13 11:36 UTC
It is not working with Archer C80 firmware 1.13.2
There are no error messages

May be related to the fact that C80 doesn’t have username, it only prompts for password

**Comment by AlexandrErohin** [comment] 2024-01-15 06:47
What error you got in the SETUP window?
What errors in Settings -> System -> Logs?

**Comment by jlguibourg** [comment] 2024-01-15 08:17
Hello

 

I don’t use windows but xubuntu 18.4 with python 3.11.4

The C80 is a the latest version.

 

I don’t have any error even with a wrong password or wrong IP address (just take more time with wrong IP address).

 

My script is as follow

from tplinkrouterc6u.client import TplinkRouter

from tplinkrouterc6u.enum import Wifi

from tplinkrouterc6u.dataclass import Firmware, Status, Device

router = TplinkRouter('http://192.168.171.203', 'mypassword')

print(router)

print("on est la")

 

# Get firmware info - returns Firmware

firmware = router.get_firmware()

print(firmware)

 

# Get status info - returns Status

status = router.get_status()

print(status)

 

The result is always

<tplinkrouterc6u.client.TplinkRouter object at 0xb79a8df0>
on est la
None
None

 

I don’t have experience with python and I don’t know how to debug.

 

There is no user name with C80 ,  see picture attached.

The alternative is with TP-link ID which is a mail address (I tried it too).



 

Regards

 

De : AlexandrErohin ***@***.*** 
Envoyé : lundi 15 janvier 2024 07:48
À : AlexandrErohin/TP-Link-Archer-C6U ***@***.***>
Cc : jlguibourg ***@***.***>; Author ***@***.***>
Objet : Re: [AlexandrErohin/TP-Link-Archer-C6U] Test with archer C80 (Issue #7)

 

What error you got in the SETUP window?
What errors in Settings -> System -> Logs?

**Comment by AlexandrErohin** [comment] 2024-01-15 09:38
to print logs - you need to pass 4th parameter 
TplinkRouter('http://192.168.0.1','password','admin2', _LOGGER)

**Comment by jlguibourg** [comment] 2024-01-15 10:00
I don’t know what to put for _LOGGER

 

router = TplinkRouter('http://192.168.171.203', ‘mypassword', 'admin2', 'log.txt')

 

I tried with log.txt and get the following result

 

python3.11 examples.py

<tplinkrouterc6u.client.TplinkRouter object at 0xb794ee10>

on est la

Traceback (most recent call last):

  File "/home/xubuntu/.local/lib/python3.11/site-packages/requests/models.py", line 971, in json

    return complexjson.loads(self.text, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode

    raise JSONDecodeError("Extra data", s, end)

json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/tplinkrouterc6u/client.py", line 174, in _request_pwd

    data = response.json()

           ^^^^^^^^^^^^^^^

  File "/home/xubuntu/.local/lib/python3.11/site-packages/requests/models.py", line 975, in json

    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

requests.exceptions.JSONDecodeError: Extra data: line 1 column 2 (char 1)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/tplinkrouterc6u/client.py", line 243, in _request

    if self.authorize():

       ^^^^^^^^^^^^^^^^

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/tplinkrouterc6u/client.py", line 73, in authorize

    self._request_pwd(referer)

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/tplinkrouterc6u/client.py", line 182, in _request_pwd

    self._logger.error('TplinkRouter Integration Exception - No pwd response - {}'.format(response.text))

    ^^^^^^^^^^^^^^^^^^

AttributeError: 'str' object has no attribute 'error'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/examples.py", line 22, in <module>

    firmware = router.get_firmware()

               ^^^^^^^^^^^^^^^^^^^^^

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/tplinkrouterc6u/client.py", line 41, in get_firmware

    return self._request(self._get_firmware)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/tplinkrouterc6u/client.py", line 251, in _request

    self._logger.error('TplinkRouter Integration Exception - {}'.format(error))

    ^^^^^^^^^^^^^^^^^^

AttributeError: 'str' object has no attribute 'error'

***@***.***:~/Scripts/TP-Link-Archer-C6U-main$ ^C

***@***.***:~/Scripts/TP-Link-Archer-C6U-main$

 

 

 

De : AlexandrErohin ***@***.*** 
Envoyé : lundi 15 janvier 2024 10:38
À : AlexandrErohin/TP-Link-Archer-C6U ***@***.***>
Cc : jlguibourg ***@***.***>; Author ***@***.***>
Objet : Re: [AlexandrErohin/TP-Link-Archer-C6U] Test with archer C80 (Issue #7)

 

to print logs - you need to pass 4th parameter
TplinkRouter('http://192.168.0.1','password','admin2', _LOGGER)

**Comment by AlexandrErohin** [comment] 2024-01-15 14:14
from logging import Logger

**Comment by jlguibourg** [comment] 2024-01-15 14:32
Sorry but I don’t understand what you mean with :  from logging import Logger

***@***.***:~/Scripts/TP-Link-Archer-C6U-main$ python3.11 examples.py

Traceback (most recent call last):

  File "/home/xubuntu/Scripts/TP-Link-Archer-C6U-main/examples.py", line 12, in <module>

    router = TplinkRouter('http://192.168.171.203', 'mypassword', 'admin2', _LOGGER)

                                                                           ^^^^^^^

NameError: name '_LOGGER' is not defined

**Comment by AlexandrErohin** [comment] 2024-01-16 13:59
from tplinkrouterc6u import TplinkRouter
from logging import Logger

client = TplinkRouter('http://192.168.171.203', 'mypassword', logger=Logger('test'))

print(client.get_status())

**Comment by jlguibourg** [comment] 2024-01-16 16:04
Here it is with 

from tplinkrouterc6u.client import TplinkRouter

from tplinkrouterc6u.client import Logger

from tplinkrouterc6u.enum import Wifi

from tplinkrouterc6u.dataclass import Firmware, Status, Device

 

client = TplinkRouter('http://192.168.171.203', 'mypassword', logger=Logger('test'))

print(client.get_status())

 

Result :

 

TplinkRouter Integration Exception - No pwd response - 00005

 

TplinkRouter Integration Exception - Unsupported router!

None

**Comment by AlexandrErohin** [comment] 2024-01-17 08:37
So your router is not supported. It would be great if you could add support for your router to this client.

**Comment by jlguibourg** [comment] 2024-01-17 09:02
Yes sure, I would like.

What is way to do it ?

**Comment by jlguibourg** [comment] 2024-01-31 07:10
How to add support for Archer C80 ?
Who could do it?
Thanks for your help

**Comment by AlexandrErohin** [comment] 2024-01-31 09:49
As I dont have Archer C80, I cannot add support for this.
If you want to add support for your router you need to trace requests from browser to your router and reconstruct them in python code

**Comment by AlexandrErohin** [comment] 2024-02-13 08:44
@jlguibourg Please try new version - As TP-link Archer C1200 v2.0 support with different login process was added - your router may also be supported now

To try client you need to get WebEncryptedPassword, please follow this instructions https://github.com/AlexandrErohin/TP-Link-Archer-C6U?tab=readme-ov-file#web-encrypted-password
```
from tplinkrouterc6u import TplinkRouterProvider
from logging import Logger

client = TplinkRouterProvider.get_client('192.168.0.1', 'WebEncryptedPassword', logger=Logger('test'))
firmware, status = client.get_full_info()

print(firmware.model)
print(firmware.hardware_version)
print(firmware.firmware_version)
print(status.lan_macaddr)
```

**Comment by jlguibourg** [comment] 2024-02-13 16:54
I get a problem with the WebEncryptedPassword

document.getElementById("login-password").value;
Uncaught TypeError: document.getElementById(...) is null
    <anonymous> debugger eval code:1

**Comment by AlexandrErohin** [comment] 2024-02-13 17:19
Could you try this steps to get WebEncryptedPassword?

1. Open the browser and go to the webinterface of you TP-link router and open the developertools(ctrl+shift+i or F12).
2. In the developertools navigate to the network tab.
3. Make sure the recoder is enabeld.
4. Login to your router
5. There should appear activity in the networking tab.
6. Scroll up until you find something like  "login?form=login" and click it.
7. Click payload, and copy the string of characters, it should be a long string.
8. This is the web encrypted password.

**Comment by jlguibourg** [comment] 2024-02-13 18:53
There is nothing such as "login?form=login" 

Everything are scripts see below

 



 



 

 

 

See what I have if I enter a wrong password

**Comment by AlexandrErohin** [comment] 2024-02-13 19:16
Lets try to add support for your router - https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/CONTRIBUTING.md

**Comment by jlguibourg** [comment] 2024-02-14 08:13
Just did it, Let me know if this is what you need.

 

I only did displays but if you are ok with the capture data, I can do more

 

De : AlexandrErohin ***@***.*** 
Envoyé : mardi 13 février 2024 20:17
À : AlexandrErohin/TP-Link-Archer-C6U ***@***.***>
Cc : jlguibourg ***@***.***>; Mention ***@***.***>
Objet : Re: [AlexandrErohin/TP-Link-Archer-C6U] Test with archer C80 (Issue #7)

 

Lets try to add support for your router - https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/CONTRIBUTING.md

**Comment by AlexandrErohin** [comment] 2024-04-19 09:01
Duplicate of https://github.com/AlexandrErohin/TP-Link-Archer-C6U/issues/11

**Closed by AlexandrErohin** 2024-04-19 09:01 UTC
